odLoader="javafml"
loaderVersion="[36,)"
# issueTrackerURL="https://github.com/Blackout03/extended-slabs/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/extended-statistics"
license="MIT License"

[[mods]]
modId="extendedstatistics"
version="${file.jarVersion}"
displayName="Extended Statistics"
authors="Blackout03"
description='''This mod adds extra statistics to the Statistics Menu.'''
itemIcon="minecraft:book_and_quill"
logoFile="icon.png"

[[dependencies.extendedstatistics]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.extendedstatistics]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
